#!/bin/sh
# P4 integration check: checks reload (classification and handling of statistics), life, restart / reset, and SIGHUP in the source container.
#
#   staging/scripts/p4-verify.sh
#
# If goipslad is already running, it aborts without changing anything, and it stops only the goipslad it started itself
# (staging/scripts/verify-lib.sh). It does not modify staging/goipslad.yaml. It puts a temporary configuration
# at staging/run/p4.yaml, passes it with --config, and rewrites it and reloads at each step. The temporary configuration
# is written inside the container (staging/run is created by root in the container, so the host may not be able to write to it).
# Takes about 1.5 minutes. JSON is checked with jq on the host.
set -u
repo=$(cd "$(dirname "$0")/../.." && pwd -P)
cd "$repo"

SOCK=/work/staging/run/goipslad.sock
LOG=/work/staging/run/goipslad-p4.log
CONF=/work/staging/run/p4.yaml

fail=0
. "$repo/staging/scripts/verify-lib.sh"
g()   { src /work/bin/goipsla --socket "$SOCK" "$@"; }
gj()  { g "$@" -o json; }
# op <id> <field path>: one value of one operation from show operations.
opval() { gj show operations | jq -r ".[] | select(.id == $1) | $2"; }
ids() { gj show operations | jq -c '[.[].id]'; }

# Stop only the goipslad this script started, and remove the temporary
# configuration (a path of this script's own).
cleanup() {
  restore_env
  src rm -f "$CONF" 2>/dev/null || true
}
trap cleanup EXIT
trap 'exit 130' INT TERM

command -v jq >/dev/null 2>&1 || { echo "p4-verify: jq is required on the host" >&2; exit 2; }

# write_config <threshold of 12> <tag of 13> <last IPv6 id> [broken]
write_config() {
  thr=$1 tag=$2 v6=$3 broken=${4:-}
  v6addr=fd00:100:1::11
  [ "$v6" = 112 ] && v6addr=fd00:100:1::12
  [ "$v6" = 113 ] && v6addr=fd00:100:1::13
  extra=
  [ "$v6" = 113 ] && extra="  - { id: 112, template: lab, target: \"fd00:100:1::12\" }"
  bad=
  [ -n "$broken" ] && bad="    request-data-size: 10   # below 28: invalid"
  src sh -c 'cat >"$0"' "$CONF" <<EOF
# generated by staging/scripts/p4-verify.sh
global:
  api-socket: $SOCK
  log: { format: text, level: info }
templates:
  lab:
    type: icmp-echo
    frequency: 2s
    timeout: 1000ms
    threshold: 100ms
    tag: lab
$bad
    history: { lives-kept: 2, buckets-kept: 15, filter: all }
operations:
  - template: lab
    targets: { 11: 10.100.1.11, 21: 10.100.2.11, 22: 10.100.2.12, 23: 10.100.2.13 }
  - { id: 12, template: lab, target: 10.100.1.12, threshold: $thr }
  - { id: 13, template: lab, target: 10.100.1.13, tag: $tag }
  - { id: 41, template: lab, target: 10.100.1.12, schedule: { life: 20s } }
  - { id: $v6, template: lab, target: "$v6addr" }
$extra
EOF
}

echo "== 1. start goipslad with a temporary configuration =="
preflight_daemon
if make build >/dev/null; then ok "make build"; else ng "make build"; exit 1; fi
src mkdir -p /work/staging/run
write_config 100ms lab 111
check "temporary configuration is valid" src /work/bin/goipsla validate "$CONF"
start_daemon "$CONF" "$LOG"
i=0
until g health >/dev/null 2>&1 || [ $i -ge 20 ]; do sleep 0.5; i=$((i + 1)); done
check "goipslad answers" g health
if ! g health >/dev/null 2>&1; then
  echo "p4-verify: goipslad did not start; see staging/run/goipslad-p4.log" >&2
  exit 1
fi
t_start=$(date +%s)
sleep 7
g show operations | indent
check "8 operations: $(ids)" jqtrue "$(gj show operations)" '[.[].id] == [11,12,13,21,22,23,41,111]'

echo "== 2. threshold of 12 changed: restarted, statistics reset; others kept =="
b11=$(opval 11 .totals.initiations)
b12=$(opval 12 .totals.initiations)
write_config 50ms lab 111
res=$(gj reload)
printf '%s\n' "$res" | jq -c . | indent
check "reload result: restarted [12] only" jqtrue "$res" '.restarted == [12] and .added == [] and .removed == [] and .updated == []'
d12=$(gj show statistics 12)
d11=$(gj show statistics 11)
check "12: new life (life_index 2), statistics from zero (was $b12 attempts)" jqtrue "$d12" '.life_index == 2 and .totals.initiations <= 1'
check "12: new threshold applied" jqtrue "$d12" '.config.threshold == "50ms"'
check "11: statistics kept ($b11 -> $(printf '%s' "$d11" | jq .totals.initiations))" jqtrue "$d11" ".life_index == 1 and .totals.initiations >= $b11"

echo "== 3. tag of 13 changed: updated, statistics kept =="
b13=$(opval 13 .totals.initiations)
write_config 50ms wan 111
res=$(gj reload)
printf '%s\n' "$res" | jq -c . | indent
check "reload result: updated [13] only" jqtrue "$res" '.updated == [13] and .restarted == [] and .added == [] and .removed == []'
d13=$(gj show statistics 13)
check "13: tag is wan" jqtrue "$d13" '.tag == "wan"'
check "13: statistics kept (life 1, $b13 -> $(printf '%s' "$d13" | jq .totals.initiations) attempts)" jqtrue "$d13" ".life_index == 1 and .totals.initiations >= $b13 and .totals.initiations > 0"
check "show operations --tag wan lists 13" jqtrue "$(gj show operations --tag wan)" '[.[].id] == [13]'

echo "== 4. 111 removed and 112 added =="
write_config 50ms wan 112
res=$(gj reload)
printf '%s\n' "$res" | jq -c . | indent
check "reload result: removed [111], added [112]" jqtrue "$res" '.removed == [111] and .added == [112] and .restarted == [] and .updated == []'
check "operations now: $(ids)" jqtrue "$(gj show operations)" '[.[].id] == [11,12,13,21,22,23,41,112]'
check "111 is gone" sh -c "! docker compose -f '$repo/staging/compose.yaml' exec -T source /work/bin/goipsla --socket $SOCK show statistics 111"

echo "== 5. invalid configuration: rejected, nothing changes =="
before=$(ids)
write_config 50ms wan 112 broken
out=$(g reload 2>&1); rc=$?
printf '%s\n' "$out" | indent
check "goipsla reload fails (exit $rc)" [ "$rc" -ne 0 ]
check "the error names the invalid field" has "$out" "request-data-size"
check "operations unchanged: $(ids)" [ "$(ids)" = "$before" ]
check "12 still measures with threshold 50ms" jqtrue "$(gj show statistics 12)" '.config.threshold == "50ms"'
write_config 50ms wan 112 # back to the valid file

echo "== 6. 41 (life 20s) becomes inactive and stops =="
now=$(date +%s)
wait_s=$((t_start + 23 - now))
[ "$wait_s" -gt 0 ] && sleep "$wait_s"
d41=$(gj show statistics 41)
g show operations | indent
check "41 is inactive" jqtrue "$d41" '.state == "inactive"'
check "41 life_left_s is 0" jqtrue "$(gj show operations)" '.[] | select(.id == 41) | .life_left_s == 0'
n41=$(printf '%s' "$d41" | jq .totals.initiations)
sleep 5
check "41 made no attempt after its life ($n41 attempts, frozen)" [ "$(opval 41 .totals.initiations)" = "$n41" ]
check "41 attempted during its life ($n41 > 5)" [ "$n41" -gt 5 ]
check "11 has no life limit (life_left_s absent)" jqtrue "$(gj show operations)" '.[] | select(.id == 11) | has("life_left_s") | not'

echo "== 7. restart and reset =="
b11=$(opval 11 .totals.initiations)
check "restart 11" g restart 11
d11=$(gj show statistics 11)
check "11: new life (life_index 2), statistics from zero (was $b11)" jqtrue "$d11" '.life_index == 2 and .totals.initiations <= 1'
out=$(g restart 41 2>&1); rc=$?
printf '%s\n' "$out" | indent
check "restart of inactive 41 is refused (exit $rc)" [ "$rc" -ne 0 ]
check "the refusal says why" has "$out" "only an active operation can be restarted"
check "reset without --yes is refused (stdin is not a terminal)" sh -c "! docker compose -f '$repo/staging/compose.yaml' exec -T source /work/bin/goipsla --socket $SOCK reset </dev/null"
sleep 3
check "reset --yes" g reset --yes
all=$(gj show operations)
check "every operation starts again from zero" jqtrue "$all" 'all(.[]; .totals.initiations <= 1)'
check "41 is active again after reset" jqtrue "$all" '.[] | select(.id == 41) | .state == "active"'

echo "== 8. SIGHUP reloads =="
write_config 50ms wan 113 # adds 113 (and keeps 112)
src kill -HUP "$own_pid"
i=0
until jqtrue "$(gj show operations)" 'any(.[]; .id == 113)' || [ $i -ge 20 ]; do sleep 0.5; i=$((i + 1)); done
check "113 added by SIGHUP: $(ids)" jqtrue "$(gj show operations)" '[.[].id] == [11,12,13,21,22,23,41,112,113]'
check "log shows the SIGHUP reload" sh -c "grep -q 'configuration reloaded.*source=sighup' '$repo/staging/run/goipslad-p4.log'"

echo "== 9. stop =="
pid=$own_pid
stop_own_daemon
check "goipslad (pid $pid) exited" own_daemon_gone "$pid"
check "clean shutdown logged" sh -c "tail -n 3 '$repo/staging/run/goipslad-p4.log' | grep -q 'goipslad stopped'"
grep -E 'reload|restart|reset|life ended|aged out' "$repo/staging/run/goipslad-p4.log" | indent

echo
[ "$fail" -eq 0 ] && echo "ALL CHECKS PASSED" || echo "SOME CHECKS FAILED"
exit "$fail"
