#!/bin/sh
# P8 load test: runs 1,000 targets x frequency 1s for 10 minutes and measures missed attempts, scheduler lag,
# CPU / memory, /metrics and show operations response times, and the goroutine and fd counts.
#
#   staging/scripts/p8-load.sh              # 600 seconds
#   LOAD_SECONDS=60 staging/scripts/p8-load.sh   # short version (for checking the script)
#
# 1. Create 1,000 targets with scale-addrs.sh add 1000 and start goipslad with frequency 1s / timeout 500ms / threshold 100ms,
#    hour group 2, enhanced history 60s x 60, and history 1 life x 60 buckets (filter all; used to measure lag).
#    metrics-listen and api-socket are enabled.
# 2. Every 30 seconds, record docker stats (source container), goipslad VmRSS and fd count,
#    process_cpu_seconds_total / process_resident_memory_bytes / go_goroutines from /metrics, and the response times of /metrics and
#    goipsla show operations -o json.
# 3. At the end, print missed attempts (difference between the expected attempts per operation and attempts_total), totals per result,
#    scheduler lag (offset of the history start times from the grid), ICMP send/receive counters and raw socket
#    drops, and the kernel ICMP rate limits.
#
# It checks the state before the run, and on exit (including interruption) restores only what it changed itself (verify-lib.sh):
# the goipslad it started, the 1,000 addresses it assigned, and the temporary configuration. If goipslad is already running
# or scale-test addresses are already assigned, it aborts without changing anything. Requires jq on the host.
set -u
repo=$(cd "$(dirname "$0")/../.." && pwd -P)
cd "$repo"

DURATION=${LOAD_SECONDS:-600}
INTERVAL=30
RUN=/work/staging/run
SOCK=$RUN/goipslad.sock
LOG=$RUN/goipslad-p8.log
CONF=$RUN/p8.yaml
URL=http://127.0.0.1:9818/metrics
# Samples and results go to $P8_OUT.* on the host (default: a new temporary
# directory, printed at the end).
OUT=${P8_OUT:-$(mktemp -d "${TMPDIR:-/tmp}/p8-load.XXXXXX")/p8}

fail=0
. "$repo/staging/scripts/verify-lib.sh"
g()   { src /work/bin/goipsla --socket "$SOCK" "$@"; }

scale_added=0

cleanup() {
  restore_env
  [ "$scale_added" -eq 1 ] && staging/scripts/scale-addrs.sh del >/dev/null 2>&1
  src rm -f "$CONF" 2>/dev/null
  true
}
trap cleanup EXIT
trap 'exit 130' INT TERM

command -v jq >/dev/null 2>&1 || { echo "p8-load: jq is required on the host" >&2; exit 2; }

# ms <command...>: run a command in the source container and print its wall time in ms.
ms() { src sh -c 's=$(date +%s%N); "$@" >/dev/null 2>&1; e=$(date +%s%N); echo $(( (e - s) / 1000000 ))' sh "$@"; }
# metric <body> <name>: the value of an unlabeled metric.
metric() { printf '%s\n' "$1" | awk -v n="$2" '$1 == n { print $2 }'; }
# icmp: the Icmp and IcmpMsg counters of the source container (name=value lines).
icmp() {
  src cat /proc/net/snmp | awk '
    /^Icmp:/ && !hdr { for (i = 2; i <= NF; i++) k[i] = $i; hdr = 1; next }
    /^Icmp:/ && hdr { for (i = 2; i <= NF; i++) print k[i] "=" $i }'
}

echo "== 1. 1,000 targets x 1 s for ${DURATION} s =="
preflight_daemon
if scale_present; then
  echo "p8-load.sh: scale test addresses (10.200.k.0/24) are already configured; run 'staging/scripts/scale-addrs.sh del' first" >&2
  exit 2
fi
if make build >/dev/null; then ok "make build (bin/metrics-get included)"; else ng "build"; exit 1; fi
if staging/scripts/scale-addrs.sh add 1000 >/dev/null; then scale_added=1; ok "scale-addrs.sh add 1000"; else ng "scale-addrs.sh add 1000"; exit 1; fi
targets=$(staging/scripts/scale-addrs.sh list | grep '^targets:')
src mkdir -p "$RUN"
src sh -c 'cat >"$0"' "$CONF" <<EOF
# generated by staging/scripts/p8-load.sh
global:
  api-socket: $SOCK
  metrics-listen: 0.0.0.0:9818
  log: { format: text, level: warn }
templates:
  load:
    type: icmp-echo
    frequency: 1s
    timeout: 500ms
    threshold: 100ms
    tag: load
    history:
      hours-of-statistics-kept: 2
      lives-kept: 1
      buckets-kept: 60
      filter: all
      enhanced: { interval: 60s, buckets: 60 }
operations:
  - template: load
    $targets
EOF
ratelimit=$(src cat /proc/sys/net/ipv4/icmp_ratelimit)
info "net.ipv4.icmp_ratelimit = $ratelimit (0: no rate limit on ICMP the kernel sends)"
icmp_before=$(icmp)
start_daemon "$CONF" "$LOG"
i=0
until g health >/dev/null 2>&1 || [ $i -ge 30 ]; do sleep 0.5; i=$((i + 1)); done
if g health >/dev/null 2>&1; then ok "goipslad (pid $own_pid) answers"; else ng "goipslad did not start"; src tail -n 20 "$LOG" | indent; exit 1; fi
t0=$(date +%s)

echo "== 2. samples every ${INTERVAL} s =="
mkdir -p "$(dirname "$OUT")"
printf 't_s\tcpu_pct\tmem_usage\tvmrss_kb\tfds\tproc_cpu_s\tproc_rss_mb\tgoroutines\tmetrics_ms\tshow_ops_ms\n' >"$OUT.samples.tsv"
while :; do
  now=$(date +%s)
  el=$((now - t0))
  st=$(docker stats --no-stream --format '{{.CPUPerc}}\t{{.MemUsage}}' ipsla-source | sed 's/ \/ .*//')
  rss=$(src awk '/^VmRSS:/ { print $2 }' "/proc/$own_pid/status")
  fds=$(src sh -c "ls /proc/$own_pid/fd | wc -l")
  body=$(src /work/bin/metrics-get -url "$URL" 2>/dev/null)
  mms=$(ms /work/bin/metrics-get -url "$URL" -q)
  sms=$(ms /work/bin/goipsla --socket "$SOCK" show operations -o json)
  cpu=$(metric "$body" process_cpu_seconds_total)
  prss=$(metric "$body" process_resident_memory_bytes | awk '{ printf "%.1f", $1 / 1048576 }')
  gor=$(metric "$body" go_goroutines)
  line=$(printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s' "$el" "$st" "$rss" "$fds" "$cpu" "$prss" "$gor" "$mms" "$sms")
  printf '%s\n' "$line" >>"$OUT.samples.tsv"
  printf '       %s\n' "$line"
  [ "$el" -ge "$DURATION" ] && break
  wait_s=$((INTERVAL - ($(date +%s) - now)))
  [ "$wait_s" -gt 0 ] && sleep "$wait_s" # a sample that took longer than the interval: go on at once
done

echo "== 3. results =="
t_end=$(date +%s)
body=$(src /work/bin/metrics-get -url "$URL" 2>/dev/null)
now_ns=$(date +%s%N)
# Missed attempts: for every operation, the attempts its life should have had
# by now (floor(elapsed) + 1, the last one possibly still running) against
# goipsla_attempts_total.
printf '%s\n' "$body" | awk -v now="$now_ns" '
  /^goipsla_life_start_timestamp_seconds\{/ { match($0, /id="[0-9]+"/); id = substr($0, RSTART + 4, RLENGTH - 5); start[id] = $NF }
  /^goipsla_attempts_total\{/ { match($0, /id="[0-9]+"/); id = substr($0, RSTART + 4, RLENGTH - 5); att[id] = $NF }
  END {
    for (id in att) {
      el = now / 1e9 - start[id]
      want = int(el) + 1
      d = want - att[id]
      n++; sumwant += want; sumatt += att[id]
      if (d > 1) { missed++; missedsum += d - 1 }
      if (d > maxd) maxd = d
    }
    printf "ops=%d expected=%d attempts=%d ops_missing_more_than_one=%d missing_total=%d max_gap=%d\n", n, sumwant, sumatt, missed + 0, missedsum + 0, maxd
  }' >"$OUT.missed.txt"
cat "$OUT.missed.txt" | indent
ops=$(g show operations -o json)
printf '%s' "$ops" | jq -c '{ops: length, initiations: (map(.totals.initiations) | add), completions: (map(.totals.completions) | add),
  over_thresholds: (map(.totals.over_thresholds) | add), timeouts: (map(.totals.timeouts) | add), busies: (map(.totals.busies) | add),
  drops: (map(.totals.drops) | add), sequence_errors: (map(.totals.sequence_errors) | add), verify_errors: (map(.totals.verify_errors) | add),
  active: (map(select(.state == "active")) | length)}' >"$OUT.totals.json"
indent <"$OUT.totals.json"
tot=$(cat "$OUT.totals.json")

# Scheduler delay: for the last 60 attempts of every operation, the time
# from its lattice point to the attempt actually starting (Result.Start =
# clk.Now() in the attempt). The history bucket index is the attempt's number
# k in the life (1, 2, ...), so its lattice point is life start + (k - 1) x
# frequency (1 s), with the life start from goipsla_life_start_timestamp_seconds.
# The difference is taken directly, so a delay of a second or more, a skipped
# lattice point (k runs behind the lattice) and a start before its lattice
# point (negative) all show and are counted separately.
printf '%s\n' "$body" | awk '/^goipsla_life_start_timestamp_seconds\{/ {
    match($0, /id="[0-9]+"/); id = substr($0, RSTART + 4, RLENGTH - 5)
    ts = $NF + 0; printf "L %s %d %.9f\n", id, int(ts), ts - int(ts) }' >"$OUT.phase.txt"
g show history -o json | jq -r '.[] | .id as $id | .life_index as $life | .history[] | select(.life == $life) |
  "S \($id) \(.bucket) \(.start | sub("\\.[0-9]+"; "") | fromdate) 0.\(.start | capture("\\.(?<f>[0-9]+)") .f // "0")"' >"$OUT.starts.txt"
cat "$OUT.phase.txt" "$OUT.starts.txt" | awk '
  $1 == "L" { ls[$2] = $3; lf[$2] = $4 + 0; next }
  $1 == "S" && ($2 in ls) {
    # delay = start - (life start + (k - 1) s), in seconds
    d = ($4 - ls[$2]) + ($5 - lf[$2]) - ($3 - 1)
    print d * 1000
  }' | sort -n >"$OUT.delay_ms.txt"
neg=$(awk '$1 < -0.01 { n++ } END { print n + 0 }' "$OUT.delay_ms.txt") # below -10 us: more than float rounding
late=$(awk '$1 >= 1000 { n++ } END { print n + 0 }' "$OUT.delay_ms.txt")
nd=$(wc -l <"$OUT.delay_ms.txt")
pct() { awk -v p="$1" -v n="$nd" 'NR == int(n * p / 100 + 0.999999) { printf "%.3f", $1; exit }' "$OUT.delay_ms.txt"; }
p50=$(pct 50); p99=$(pct 99); p999=$(pct 99.9); pmax=$(tail -n 1 "$OUT.delay_ms.txt" | awk '{ printf "%.3f", $1 }')
pmin=$(head -n 1 "$OUT.delay_ms.txt" | awk '{ printf "%.3f", $1 }')
info "scheduler delay over $nd attempts (ms from the lattice point): min $pmin, p50 $p50, p99 $p99, p99.9 $p999, max $pmax"
info "attempts that started before their lattice point (< -0.01 ms): $neg; 1 s or more after it: $late"

icmp_after=$(icmp)
for k in OutMsgs OutEchos InEchoReps InDestUnreachs OutErrors InErrors InCsumErrors; do
  b=$(printf '%s\n' "$icmp_before" | awk -F= -v k="$k" '$1 == k { print $2 }')
  a=$(printf '%s\n' "$icmp_after" | awk -F= -v k="$k" '$1 == k { print $2 }')
  [ -n "$a" ] && info "Icmp $k: +$((a - ${b:-0}))"
done
drops=$(src awk 'NR > 1 { s += $NF } END { print s + 0 }' /proc/net/raw /proc/net/raw6)
info "raw socket drops (/proc/net/raw, raw6): $drops"
printf '%s\n' "$body" | grep -E '^go_goroutines |^process_open_fds |^process_resident_memory_bytes |^process_cpu_seconds_total |^goipsla_scrape_duration_seconds ' | indent

echo "== 4. checks =="
elapsed=$((t_end - t0))
tot_init=$(printf '%s' "$tot" | jq .initiations)
check_zero() { v=$(printf '%s' "$tot" | jq ".$1"); [ "$v" = 0 ] && ok "$1: 0" || ng "$1: $v"; }
[ "$(printf '%s' "$tot" | jq .ops)" = 1000 ] && ok "1000 operations" || ng "operations: $(printf '%s' "$tot" | jq .ops)"
missing=$(sed -n 's/.*ops_missing_more_than_one=\([0-9]*\).*/\1/p' "$OUT.missed.txt")
[ "$missing" = 0 ] && ok "no operation missed an attempt (initiations $tot_init over ${elapsed} s)" || ng "$missing operations missed attempts: $(cat "$OUT.missed.txt")"
check_zero busies
check_zero drops
check_zero timeouts
check_zero sequence_errors
[ "$drops" = 0 ] && ok "raw sockets dropped nothing" || ng "raw socket drops: $drops"
awk -v p="$p99" 'BEGIN { exit !(p + 0 < 100) }' && ok "scheduler delay p99 $p99 ms (< 100 ms)" || ng "scheduler delay p99 $p99 ms"
[ "$nd" -ge 50000 ] && ok "delay measured over $nd attempts" || ng "delay measured over only $nd attempts"
[ "$neg" = 0 ] && ok "no attempt started before its lattice point" || ng "$neg attempts started before their lattice point"
[ "$late" = 0 ] && ok "no attempt started 1 s or more late (no skipped lattice point)" || ng "$late attempts started 1 s or more late"
maxm=$(awk -F'\t' 'NR > 1 && $9 > m { m = $9 } END { print m + 0 }' "$OUT.samples.tsv")
maxs=$(awk -F'\t' 'NR > 1 && $10 > m { m = $10 } END { print m + 0 }' "$OUT.samples.tsv")
[ "$maxm" -lt 1000 ] && ok "/metrics at most $maxm ms" || ng "/metrics took $maxm ms"
[ "$maxs" -lt 1000 ] && ok "show operations -o json at most $maxs ms" || ng "show operations took $maxs ms"
g0=$(awk -F'\t' 'NR == 2 { print $8 }' "$OUT.samples.tsv"); g1=$(awk -F'\t' 'END { print $8 }' "$OUT.samples.tsv")
f0=$(awk -F'\t' 'NR == 2 { print $5 }' "$OUT.samples.tsv"); f1=$(awk -F'\t' 'END { print $5 }' "$OUT.samples.tsv")
info "goroutines $g0 -> $g1, fds $f0 -> $f1"

echo "== 5. restore =="
pid=$own_pid
stop_own_daemon
own_daemon_gone "$pid" && ok "goipslad (pid $pid) exited" || ng "goipslad (pid $pid) still running"
if staging/scripts/scale-addrs.sh del >/dev/null; then scale_added=0; fi
scale_present && ng "scale addresses remain" || ok "scale-addrs.sh del: scale addresses removed"
echo "       samples and results: $OUT.*"

echo
[ "$fail" -eq 0 ] && echo "ALL CHECKS PASSED" || echo "SOME CHECKS FAILED"
exit "$fail"
